import "./components/header";
import "./components/main";
import "./components/cards";
import "./components/footer";
import "./utils/search";
import "./utils/addInCart";
import "./components/cart";
import "./components/сartItems";
import "./components/preloader";
